Adding stringio for security reasons
krkn-chaos/krkn pull request #316
Opened 2022-09-02 17:00 UTC by paigerube14

## Description
There needed security updates to not use a file written to /tmp file. I am now using a stringio buffer to write and update the status

There was also a unset reference to a variable called litmus_installed at the very end of the run_kraken script. I added a default value and update if litmus is installed

## Fixes 
https://github.com/redhat-chaos/krkn/issues/303

2022-09-03 07:24 UTC, ghost requested changes

2022-09-09 17:12 UTC, paigerube14 commented on server.py
> +        output.seek(0)
updated to just use a global variable here, ptal

2022-09-09 18:48 UTC, ghost approved these changes

2022-09-09 19:09 UTC, chaitanyaenr approved these changes
LGTM

2022-09-09 19:10 UTC, chaitanyaenr commented
@paigerube14 PR needs rebase.

2022-09-12 15:14 UTC, merged