Adding proxy settings to client setting
krkn-chaos/krkn pull request #349
Opened 2022-11-02 14:47 UTC by paigerube14

Adding the same kubernetes config I added to cerberus in [PR](https://github.com/redhat-chaos/cerberus/pull/184) here, waiting for a private cluster to double check this. Will update if this doesn't work

2022-11-07 06:39 UTC, sandrobonazzola requested changes
inline comments

2022-11-07 06:39 UTC, sandrobonazzola commented on kraken/kubernetes/client.py
> +        """Initialize object and create clients from specified kubeconfig"""
Sounds like this should be a comment rather than a string

2022-11-07 06:39 UTC, sandrobonazzola commented on kraken/kubernetes/client.py
> +        """Proxy has auth header"""
here as well

2022-11-07 14:53 UTC, chaitanyaenr approved these changes
LGTM. Have not tested it though. Thanks.

2022-11-10 07:31 UTC, ghost requested changes

2022-11-15 20:54 UTC, paigerube14 commented on kraken/kubernetes/client.py
> +            proxy_auth = http_proxy.split("@")[0].split("//")[1]
Updated!

2022-11-30 16:22 UTC, chaitanyaenr commented
@paigerube14 let's rebase the PR.

2022-11-30 16:36 UTC, ghost approved these changes

2022-12-01 16:13 UTC, paigerube14 commented on kraken/kubernetes/client.py
> +            auth_string = proxy_auth.username + ":" +  proxy_auth.password
Do you mean something like the below? I see a lot of references using that chardet python package but not sure if you have something else in mind

```
import chardet
the_encoding = chardet.detect('your string')['encoding']
string.decode(the_encoding)
```

2023-12-14 08:26 UTC, tsebastiani commented
/funtest

2024-02-09 16:25 UTC, paigerube14 commented
closing as this functionality has moved to krkn-lib, will want to move the functionality over there

2024-02-09 17:04 UTC, closed without merging